Document: bloonix-plugins-drbd
Title: Debian bloonix-plugins-drbd Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-drbd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-drbd/bloonix-plugins-drbd.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-drbd/bloonix-plugins-drbd.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-drbd/bloonix-plugins-drbd.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-drbd/html/index.html
Files: /usr/share/doc/bloonix-plugins-drbd/html/*.html


